import asyncActionType from "../utils/reduxActions";

export const FILTER_ACTIONS = {
  GET_MARKETING_BUSINESS_REPORTS: asyncActionType(
    "[IRES]GET_MARKETING_BUSINESS_REPORTS"
  ),

  DARK_MODE: asyncActionType("[IRES]DARK_MODE"),

  GET_MARKETING_BUSINESS_REPORTS_CALL:
    "[IRES]GET_MARKETING_BUSINESS_REPORTS_CALL",
  GET_RANKING_REPORTS: asyncActionType("[IRES]GET_RANKING_REPORTS"),
  GET_RANKING_REPORTS_CALL: "[IRES]GET_RANKING_REPORTS_CALL",

  GET_CONVERSATION_DETAILS: asyncActionType("[IRES]GET_CONVERSATION_DETAILS"),
  GET_CONVERSATION_DETAILS_CALL: "[IRES]GET_CONVERSATION_DETAILS_CALL",

  GET_CONVERSATION_INSIGHTS: asyncActionType("[IRES]GET_CONVERSATION_INSIGHTS"),
  GET_CONVERSATION_INSIGHTS_CALL: "[IRES]GET_CONVERSATION_INSIGHTS_CALL",

  SET_TOAST_MESSAGE: "[VERTEX360]SET_TOAST_MESSAGE",
  CLEAR_TOAST_MESSAGE: "[VERTEX360]CLEAR_TOAST_MESSAGE",

  SEND_OTP_FOR_CONFIRMATION: asyncActionType("[IRES]SEND_OTP_FOR_CONFIRMATION"),
  SEND_OTP_FOR_CONFIRMATION_CALL: "[IRES]SEND_OTP_FOR_CONFIRMATION_CALL",

  SEND_OTP: asyncActionType("[IRES]SEND_OTP"),
  SEND_OTP_CALL: "[IRES]SEND_OTP_CALL",

  GET_DASHBOARD_ARO_REV_CUST: asyncActionType(
    "[IRES]GET_DASHBOARD_ARO_REV_CUST"
  ),

  GET_DASHBOARD_ARO_REV_CUST_CALL: "[IRES]GET_DASHBOARD_ARO_REV_CUST_CALL",

  GET_DASHBOARD_AI_DATA: asyncActionType("[IRES]GET_DASHBOARD_AI_DATA"),
  GET_DASHBOARD_AI_DATA_CALL: "[IRES]GET_DASHBOARD_AI_DATA",

  GET_DASHBOARD_SANKYCHART_DATA: asyncActionType(
    "[IRES]GET_DASHBOARD_SANKYCHART_DATA"
  ),
  GET_DASHBOARD_SANKYCHART_DATA_CALL: "GET_DASHBOARD_SANKYCHART_DATA",

  GET_ADWORDS_CTR_ARO_CALLS_ROI: asyncActionType(
    "[IRES]GET_ADWORDS_CTR_ARO_CALLS_ROI"
  ),
  GET_ADWORDS_CTR_ARO_CALLS_ROI_CALL:
    "[IRES]GET_ADWORDS_CTR_ARO_CALLS_ROI_CALL",

  GET_ADWORDS_CTR_ARO_CALLS: asyncActionType("[IRES]GET_ADWORDS_CTR_ARO_CALLS"),
  GET_ADWORDS_CTR_ARO_CALLS_CALL: "[IRES]GET_ADWORDS_CTR_ARO_CALLS_CALL",

  GET_ADWORDS_CTR_INVEST_RATE: asyncActionType(
    "[IRES]GET_ADWORDS_CTR_INVEST_RATE"
  ),
  GET_ADWORDS_CTR_INVEST_RATE_CALL: "[IRES]GET_ADWORDS_CTR_INVEST_RATE_CALL",

  GET_DASHBOARD_REV_CAR_ARO: asyncActionType("[IRES]GET_DASHBOARD_REV_CAR_ARO"),
  GET_DASHBOARD_REV_CAR_ARO_CALL: "[IRES]GET_DASHBOARD_REV_CAR_ARO_CALL",

  GET_YELP_CUSTOMER_CALL_APTS: asyncActionType(
    "[IRES]GET_YELP_CUSTOMER_CALL_APTS"
  ),
  GET_YELP_CUSTOMER_CALL_APTS_CALL: "[IRES]GET_YELP_CUSTOMER_CALL_APTS_CALL",

  GET_YELP_PAGE_VISITS: asyncActionType("[IRES]GET_YELP_PAGE_VISITS"),
  GET_YELP_PAGE_VISITS_CALL: "[IRES]GET_YELP_PAGE_VISITS_CALL",

  GET_YELP_COST_PER_LEAD: asyncActionType("[IRES]GET_YELP_COST_PER_LEAD"),
  GET_YELP_COST_PER_LEAD_CALL: "[IRES]GET_YELP_COST_PER_LEAD_CALL",

  GET_YELP_CONVERSATION_RATE: asyncActionType(
    "[IRES]GET_YELP_CONVERSATION_RATE"
  ),
  GET_YELP_CONVERSATION_RATE_CALL: "[IRES]GET_YELP_CONVERSATION_RATE_CALL",

  GET_YELP_CTR_PER_CLICKS: asyncActionType("[IRES]GET_YELP_CTR_PER_CLICKS"),
  GET_YELP_CTR_PER_CLICKS_CALL: "[IRES]GET_YELP_CTR_PER_CLICKS_CALL",

  GET_REFERAL_REVENUE_DATA: asyncActionType("[IRES]GET_REFERAL_REVENUE_DATA"),
  GET_REFERAL_REVENUE_DATA_CALL: "[IRES]GET_REFERAL_REVENUE_DATA_CALL",

  CHAERT_DATA_FOR_YELP: "CHAERT_DATA_FOR_YELP",

  GET_YELP_ROI: asyncActionType("[IRES]GET_YELP_ROI"),
  GET_YELP_ROI_CALL: "[IRES]GET_YELP_ROI_CALL",

  RESEND_VERIFICATION_CODE: asyncActionType("[IRES]RESEND_VERIFICATION_CODE"),
  RESEND_VERIFICATION_CODE_CALL: "[IRES]RESEND_VERIFICATION_CODE_CALL",

  GET_REPAIRPAL_REVENUE_DATA: asyncActionType(
    "[IRES]GET_REPAIRPAL_REVENUE_DATA"
  ),
  GET_REPAIRPAL_REVENUE_DATA_CALL: "[IRES]GET_REPAIRPAL_REVENUE_DATA_CALL",

  GET_REPAIRPAL_INVESTMENT_DATA: asyncActionType(
    "[IRES]GET_REPAIRPAL_INVESTMENT_DATA"
  ),
  GET_REPAIRPAL_INVESTMENT_DATA_CALL:
    "[IRES]GET_REPAIRPAL_INVESTMENT_DATA_CALL",

  GET_BOOKED_APPOINTMENT_CHARTS_DATA: asyncActionType(
    "[IRES]GET_BOOKED_APPOINTMENT_CHARTS_DATA"
  ),
  GET_BOOKED_APPOINTMENT_CHARTS_DATA_CALL:
    "[IRES]GET_BOOKED_APPOINTMENT_CHARTS_DATA_CALL",

  GET_UNSCORED_CALLS: asyncActionType("[IRES]GET_UNSCORED_CALLS"),
  GET_UNSCORED_CALLS_CALL: "[IRES]GET_UNSCORED_CALLS_CALL",

  GET_COUNT_PER_CALL_DATA: asyncActionType("[IRES]GET_COUNT_PER_CALL_DATA"),
  GET_COUNT_PER_CALL_DATA_CALL: "[IRES]GET_COUNT_PER_CALL_DATA_CALL",

  GET_SHOW_NOSHOW_DATA: asyncActionType("[IRES]GET_SHOW_NOSHOW_DATA"),
  GET_SHOW_NOSHOW_DATA_CALL: "[IRES]GET_SHOW_NOSHOW_DATA_CALL",

  GET_UNMATCHED_CUSTOMERS: asyncActionType("[IRES]GET_UNMATCHED_CUSTOMERS"),
  GET_UNMATCHED_CUSTOMERS_CALL: "[IRES]GET_UNMATCHED_CUSTOMERS_CALL",

  GET_COACHING_INSIGHT_CALL_DATA: asyncActionType(
    "[IRES]GET_COACHING_INSIGHT_CALL_DATA"
  ),
  GET_COACHING_INSIGHT_CALL_DATA_CALL:
    "[IRES]GET_COACHING_INSIGHT_CALL_DATA_CALL",

  GET_REVENUE_AND_CUSTOMER_DATA: asyncActionType(
    "[IRES]GET_REVENUE_AND_CUSTOMER_DATA"
  ),
  GET_REVENUE_AND_CUSTOMER_DATA_CALL:
    "[IRES]GET_REVENUE_AND_CUSTOMER_DATA_CALL",

  GET_NO_BOOKED_APPTS_DATA: asyncActionType("[IRES]GET_NO_BOOKED_APPTS_DATA"),
  GET_NO_BOOKED_APPTS_DATA_CALL: "[IRES]GET_NO_BOOKED_APPTS_DATA_CALL",

  GET_BOOKED_APPTS_DATA: asyncActionType("[IRES]GET_BOOKED_APPTS_DATA"),
  GET_BOOKED_APPTS_DATA_CALL: "[IRES]GET_BOOKED_APPTS_DATA_CALL",

  RESEND_OTP: asyncActionType("[IRES]RESEND_OTP"),
  RESEND_OTP_CALL: "[IRES]RESEND_OTP_CALL",

  RESET_PASSWORD: asyncActionType("[IRES]RESET_PASSWORD"),
  RESET_PASSWORD_CALL: "[IRES]RESET_PASSWORD_CALL",

  LOGIN: asyncActionType("[IRES]LOGIN"),
  LOGIN_CALL: "[IRES]LOGIN_CALL",

  LOGOUT_BEGIN: "[IRES]LOGOUT_BEGIN_CALL",
  LOGOUT: asyncActionType("[IRES]LOGOUT"),

  UPDATE_AUTH_USER: "[IRES]UPDATE_AUTH_USER",

  AUTHENTICATED_USER: "[IRES]AUTHENTICATED_USER",

  GET_FILTER_SERVICE_ADVISOR: asyncActionType(
    "[IRES]GET_FILTER_SERVICE_ADVISOR"
  ),
  GET_FILTER_SERVICE_ADVISOR_CALL: "[IRES]GET_FILTER_SERVICE_ADVISOR_CALL"
};

export const FETCH_STATUS = {
  LOADING: "LOADING",
  SUCCESS: "SUCCESS",
  ERROR: "ERROR"
};

export default {
  ...FILTER_ACTIONS
};

export const LOADER_STATUS = {
  NA: -1,
  PENDING: 1,
  COMPLETE: 0
};
