import { ReactComponent as icon_dashboard } from "../assets/icons/sidebar/icon_dashboard.svg";
import { ReactComponent as icon_conversationInsights } from "../assets/icons/sidebar/icon_conversationInsights.svg";
import { ReactComponent as icon_conversationDetails } from "../assets/icons/sidebar/icon_conversationDetails.svg";
import { ReactComponent as icon_report } from "../assets/icons/sidebar/icon_report.svg";
import { ReactComponent as icon_setting } from "../assets/icons/sidebar/icon_setting.svg";
import { ReactComponent as icon_repairpal } from "../assets/icons/sidebar/icon_repairPal.svg";
import { ReactComponent as icon_yelp } from "../assets/icons/sidebar/icon_yelp.svg";
import { ReactComponent as icon_adwords } from "../assets/icons/sidebar/icon_adwords.svg";
import { ReactComponent as icon_revenueCustomerCampaign } from "../assets/icons/sidebar/icon_revenueCustomerCampaign.svg";

export const ifmcUsers = [
  "frankn@autocarefl.com",
  "andrewt@autocarefl.com",
  "erics@autocarefl.com",
];

export const ifcUsers = [
  "r.eric@guestx.co",
  // "karl@interstateautocare.com",
  "nick@interstateautocare.com",
  "bill@interstateautocare.com",
];

const countries = [
  "Afghanistan",

  "England",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czechia",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "East Timor (Timor-Leste)",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Ivory Coast",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea, North",
  "Korea, South",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar (Burma)",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Macedonia (formerly Macedonia)",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

export default countries;

export const sidebar_settings = {
  img: icon_setting,
  title: "Settings",
  route: "/settings",
  link: "navigate",
  selected: false,
};

// export const sidebar_images = [
//   {
//     img: icon_dashboard,
//     title: "Dashboard",
//     route: "/dashboard",
//     link: "navigate",
//     selected: false
//   },
//   {
//     img: icon_conversationInsights,
//     title: "Conversation Insights",
//     route: "/callInsights",
//     link: "navigate",
//     selected: false
//   },
//   {
//     img: icon_conversationDetails,
//     title: "Conversation Details",
//     route: "/conversationDetails",
//     link: "navigate",
//     selected: false
//   },
//   {
//     img: icon_report,
//     title: "Reports",
//     route: "/report",
//     link: "navigate",
//     selected: false,
//     submenu: [
//       {
//         title: "Business Reports",
//         route: "/report/business_report",
//         ink: "navigate"
//       },
//       {
//         title: "Ranking Reports",
//         route: "/report/ranking_report",
//         ink: "navigate"
//       }
//     ]
//   }
//   // {
//   //   img: icon_repairpal,
//   //   title: "RepairPal",
//   //   route: "/repairPal",
//   //   link: "navigate",
//   //   selected: false,
//   // },
//   // {
//   //   img: icon_yelp,
//   //   title: "Yelp",
//   //   route: "/yelp",
//   //   link: "navigate",
//   //   selected: false,
//   // },
//   // {
//   //   img: icon_adwords,
//   //   title: "Adwords",
//   //   route: "/adwords",
//   //   link: "navigate",
//   //   selected: false,
//   // },
//   // {
//   //   img: icon_revenueCustomerCampaign,
//   //   title: "Revenue, Customer, Campaign",
//   //   route: "/revenue_customer_campaign",
//   //   link: "navigate",
//   //   selected: false,
//   // },
//   // {
//   //   img: image7,
//   //   title: "CallAnalytics",
//   //   route: "callAnalytics",
//   //   link: "navigate",
//   //   selected: false,
//   // },
// ];

export const sidebar_images = [
  {
    name: "Dashboard",
    href: "/dashboard",
    icon: icon_dashboard,
    // count: "5",
    current: true,
  },
  {
    icon: icon_conversationInsights,
    name: "Conversation Insights",
    href: "/callInsights",
    current: true,
  },
  {
    icon: icon_conversationDetails,
    name: "Conversation Details",
    href: "/conversationDetails",

    current: true,
  },
  {
    icon: icon_report,
    name: "Reports",
    href: "/report",
    current: true,
    submenu: [
      {
        name: "Business Reports",
        href: "/report/business_report",
        ink: "navigate",
      },
      {
        name: "Ranking Reports",
        href: "/report/ranking_report",
        ink: "navigate",
      },
    ],
  },
];
export const EMAIL_REGEX_EXP = /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i;
export const DUMMY_REGEX_EXP = /^\w+([.-]?\w+)*@\w+([.-]?\w+)*(\.\w{2,3})+$/;

export const emptyPaginationObj = {
  page: 1,
  totalPages: 0,
  total: 0,
  sort_type: null,
  sort_field: null,
  filter: null,
};

export const TOAST_TYPE = {
  DEFAULT: "default",
  SUCCESS: "success",
  ERROR: "error",
};
